spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carapp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL82Dialect
      '[format_sql]': false
    open-in-view: false
